#!/usr/bin/env bash
# Portable bootstrap for axentx surrogate-1-harvest pipeline.
#
# Run this on a FRESH host to install everything needed: Python venv,
# system deps, repo clone, systemd units, daemons. Idempotent — safe
# to re-run.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/<user>/<repo>/main/deploy/portable-bootstrap.sh | bash
#   OR
#   git clone <repo>.git /opt/surrogate-1-harvest
#   sudo bash /opt/surrogate-1-harvest/deploy/portable-bootstrap.sh
#
# Environment variables (all optional; defaults work for fresh Ubuntu/Debian):
#   AXENTX_REPO        — git URL (default: $(git config --get remote.origin.url))
#   AXENTX_BRANCH      — branch to deploy (default: main)
#   AXENTX_USER        — runtime user (default: $SUDO_USER or ubuntu)
#   AXENTX_HOME        — install root (default: /opt/surrogate-1-harvest)
#   AXENTX_ENV_FILE    — env file path (default: /etc/surrogate-coordinator.env)
#   AXENTX_TIER        — host tier: gcp-micro|kam-2gb|oci-arm|generic (default: generic)
#                        Tier sets which daemons to enable (memory budget).
#   SKIP_PKG_INSTALL=1 — skip apt install step
#   SKIP_DAEMONS=1     — install code only, don't start daemons (dry-run)
#
# Exit codes:
#   0  — full success, all daemons active
#   2  — partial success (some daemons failed to start; see journalctl)
#   3  — fatal: env file missing required keys
#   4  — fatal: systemctl daemon-reload failed
set -euo pipefail

readonly REPO_URL="${AXENTX_REPO:-}"
readonly BRANCH="${AXENTX_BRANCH:-main}"
readonly RUN_USER="${AXENTX_USER:-${SUDO_USER:-ubuntu}}"
readonly INSTALL_DIR="${AXENTX_HOME:-/opt/surrogate-1-harvest}"
readonly ENV_FILE="${AXENTX_ENV_FILE:-/etc/surrogate-coordinator.env}"
readonly TIER="${AXENTX_TIER:-generic}"

log()  { printf '[%(%H:%M:%S)T] %s\n' -1 "$*" >&2; }
fail() { log "FATAL: $*"; exit "${2:-1}"; }

[[ $EUID -eq 0 ]] || fail "must run as root (use sudo)"

# ── 1. System deps ──────────────────────────────────────────────────────────
if [[ "${SKIP_PKG_INSTALL:-0}" != "1" ]]; then
    log "installing system deps (apt)"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -y --no-install-recommends \
        python3 python3-venv python3-pip git curl jq sqlite3 \
        redis-server tini ca-certificates gnupg \
        >/dev/null
    systemctl enable --now redis-server || true
fi

# ── 2. User ─────────────────────────────────────────────────────────────────
if ! id "$RUN_USER" &>/dev/null; then
    log "creating user: $RUN_USER"
    useradd -m -s /bin/bash "$RUN_USER"
fi

# ── 3. Clone or update repo ─────────────────────────────────────────────────
if [[ ! -d "$INSTALL_DIR/.git" ]]; then
    if [[ -d "$INSTALL_DIR/bin" ]] && ls "$INSTALL_DIR"/bin/axentx-*-daemon.py >/dev/null 2>&1; then
        log "$INSTALL_DIR exists with axentx daemons but no .git — assume rsync'd, skip clone"
    elif [[ -n "$REPO_URL" ]]; then
        log "cloning $REPO_URL → $INSTALL_DIR"
        git clone --depth 50 -b "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
    else
        fail "AXENTX_REPO not set and $INSTALL_DIR not a git repo and no rsync'd content"
    fi
else
    log "updating $INSTALL_DIR (git pull --rebase)"
    git -C "$INSTALL_DIR" fetch --quiet origin "$BRANCH"
    git -C "$INSTALL_DIR" reset --hard "origin/$BRANCH"
fi
chown -R "$RUN_USER":"$RUN_USER" "$INSTALL_DIR"

# ── 4. Python venv ──────────────────────────────────────────────────────────
log "ensuring Python venv at $INSTALL_DIR/.venv"
sudo -u "$RUN_USER" python3 -m venv "$INSTALL_DIR/.venv"
sudo -u "$RUN_USER" "$INSTALL_DIR/.venv/bin/pip" install --quiet --upgrade pip wheel
sudo -u "$RUN_USER" "$INSTALL_DIR/.venv/bin/pip" install --quiet -r "$INSTALL_DIR/requirements.txt"

# ── 5. Env file ─────────────────────────────────────────────────────────────
# Required keys for the pipeline to function. If env file is missing or
# stub, write a template so operator can fill in.
required_keys=(
    SUPABASE_URL SUPABASE_ANON_KEY
    GITHUB_TOKEN HF_TOKEN
    DISCORD_WEBHOOK
    CEREBRAS_API_KEY GROQ_API_KEY OPENROUTER_API_KEY
)
optional_keys=(
    SAMBANOVA_API_KEY NVIDIA_API_KEY GEMINI_API_KEY
    CLOUDFLARE_API_TOKEN CLOUDFLARE_ACCOUNT_ID
    DEEPSEEK_API_KEY TOGETHER_API_KEY MISTRAL_API_KEY
    GITHUB_MODELS_TOKEN
)
if [[ ! -f "$ENV_FILE" ]]; then
    log "writing env template → $ENV_FILE (REQUIRES OPERATOR EDIT)"
    {
        echo "# axentx surrogate-1-harvest env — fill in before starting daemons"
        echo "# Generated by portable-bootstrap.sh on $(date -Iseconds)"
        echo "# REQUIRED:"
        for k in "${required_keys[@]}"; do echo "$k="; done
        echo "# OPTIONAL (more providers = more headroom):"
        for k in "${optional_keys[@]}"; do echo "$k="; done
    } > "$ENV_FILE"
    chmod 600 "$ENV_FILE"
fi

# Validate required keys are non-empty
missing=()
for k in "${required_keys[@]}"; do
    v=$(grep -E "^${k}=" "$ENV_FILE" | head -1 | cut -d= -f2-)
    [[ -n "$v" ]] || missing+=("$k")
done
if [[ ${#missing[@]} -gt 0 ]]; then
    log "WARN: env file missing values for: ${missing[*]}"
    log "     edit $ENV_FILE then re-run with SKIP_PKG_INSTALL=1"
    if [[ "${SKIP_DAEMONS:-0}" != "1" ]]; then
        fail "refusing to start daemons with incomplete env" 3
    fi
fi

# ── 6. State + workspace dirs ───────────────────────────────────────────────
sudo -u "$RUN_USER" mkdir -p \
    "$INSTALL_DIR/state" "$INSTALL_DIR/logs" "$INSTALL_DIR/data" \
    "/home/$RUN_USER/.surrogate/state" "/home/$RUN_USER/.surrogate/logs" \
    "/home/$RUN_USER/axentx" "/opt/axentx"
chown -R "$RUN_USER":"$RUN_USER" "/opt/axentx" 2>/dev/null || true

# ── 7. Tier-aware daemon list ───────────────────────────────────────────────
# Always-on (cheap, essential):
core_daemons=(
    axentx-cost-guard-daemon
    axentx-disk-janitor-daemon
    axentx-discord-notifier-daemon
    axentx-aux-orchestrator-daemon
    axentx-scrape-orchestrator-daemon
    axentx-reddit-stream-daemon
    axentx-github-deep-stream-daemon
    axentx-pain-validator-daemon
    axentx-market-research-daemon
    axentx-bd-daemon
    axentx-product-spawner-daemon
    axentx-business-synthesis-daemon
    axentx-design-thinking-daemon
    axentx-architect-daemon
    axentx-ux-daemon
    axentx-prd-daemon
    axentx-feature-builder-daemon
    axentx-reviewer-daemon
    axentx-qa-daemon
    axentx-commit-daemon
    axentx-mvp-validator-daemon
    axentx-release-daemon
    axentx-hf-flusher-daemon
)
# Template instances — daemon@1, @2, @3 patterns. Each instance claims
# a separate worker slot and runs in parallel. dev-daemon does the
# actual code-writing work; research-daemon pulls fresh raw signals.
# Counts tuned by tier: more workers = faster drain, more memory.
case "$TIER" in
    gcp-micro|kam-2gb)  template_instances=1 ;;
    oci-arm)            template_instances=4 ;;
    *)                  template_instances=2 ;;
esac
template_units=(
    "axentx-dev-daemon"
    "axentx-research-daemon"
)
# Optional (heavier — skip on micro tier):
optional_daemons=(
    axentx-bucket-archiver-daemon
    axentx-dataset-mirror-daemon
    axentx-customer-poll-daemon
    axentx-canary-daemon
    axentx-content-daemon
    axentx-docs-daemon
    axentx-business-daemon
    axentx-marketing-daemon
    axentx-perf-daemon
    axentx-pm-daemon
    axentx-security-daemon
    axentx-skill-synthesizer-daemon
    axentx-support-inbox-daemon
    axentx-trends-daemon
    axentx-incident-responder-daemon
    axentx-feature-builder-daemon
    axentx-scheduled-runner-daemon
    axentx-v1-warmup-daemon
)

case "$TIER" in
    gcp-micro|kam-2gb)
        # Memory-tight: core only
        daemons=("${core_daemons[@]}")
        log "TIER=$TIER → core daemons only (${#daemons[@]} units)"
        ;;
    oci-arm|generic|*)
        daemons=("${core_daemons[@]}" "${optional_daemons[@]}")
        log "TIER=$TIER → all daemons (${#daemons[@]} units)"
        ;;
esac

# ── 8. Install systemd units ────────────────────────────────────────────────
# Substitute User= and WorkingDirectory= and EnvironmentFile= so units
# work on any host without manual edits.
log "installing systemd units → /etc/systemd/system/"
unit_count=0
render_unit() {
    local src="$1" dst="$2"
    sed -e "s|^User=.*|User=$RUN_USER|" \
        -e "s|^WorkingDirectory=.*|WorkingDirectory=$INSTALL_DIR|" \
        -e "s|^EnvironmentFile=.*|EnvironmentFile=$ENV_FILE|" \
        -e "s|REPO_ROOT=/opt/surrogate-1-harvest|REPO_ROOT=$INSTALL_DIR|g" \
        -e "s|/opt/surrogate-1-harvest/.venv/bin/python|$INSTALL_DIR/.venv/bin/python|g" \
        -e "s|/opt/surrogate-1-harvest/bin|$INSTALL_DIR/bin|g" \
        "$src" > "$dst"
    chmod 644 "$dst"
}
for d in "${daemons[@]}"; do
    src="$INSTALL_DIR/systemd/${d}.service"
    [[ -f "$src" ]] || { log "  skip: $src not found"; continue; }
    render_unit "$src" "/etc/systemd/system/${d}.service"
    unit_count=$((unit_count + 1))
done
# Install template units (axentx-dev-daemon@.service etc.)
for t in "${template_units[@]}"; do
    src="$INSTALL_DIR/systemd/${t}@.service"
    [[ -f "$src" ]] || continue
    render_unit "$src" "/etc/systemd/system/${t}@.service"
    unit_count=$((unit_count + 1))
done
log "installed $unit_count units (incl. ${#template_units[@]} templates × $template_instances instances)"

systemctl daemon-reload || fail "systemctl daemon-reload failed" 4

# ── 9. Enable + start ───────────────────────────────────────────────────────
if [[ "${SKIP_DAEMONS:-0}" == "1" ]]; then
    log "SKIP_DAEMONS=1 — code installed but not started"
    log "to start: systemctl enable --now axentx-cost-guard-daemon ..."
    exit 0
fi

# Cost-guard FIRST — enforces free-only before anything spends money
log "starting cost-guard FIRST (enforces free-only rule)"
systemctl enable --now axentx-cost-guard-daemon || \
    log "  ⚠ cost-guard failed to start — review immediately"

failed=()
for d in "${daemons[@]}"; do
    [[ "$d" == "axentx-cost-guard-daemon" ]] && continue
    if [[ -f "/etc/systemd/system/${d}.service" ]]; then
        if systemctl enable --now "$d" 2>/dev/null; then
            :
        else
            failed+=("$d")
        fi
    fi
done
# Enable template instances
for t in "${template_units[@]}"; do
    [[ -f "/etc/systemd/system/${t}@.service" ]] || continue
    for i in $(seq 1 "$template_instances"); do
        if systemctl enable --now "${t}@${i}.service" 2>/dev/null; then
            :
        else
            failed+=("${t}@${i}")
        fi
    done
done

# ── 10. Health check ─────────────────────────────────────────────────────────
sleep 8   # let daemons settle
active=0
inactive=()
for d in "${daemons[@]}"; do
    [[ -f "/etc/systemd/system/${d}.service" ]] || continue
    if systemctl is-active --quiet "$d"; then
        active=$((active + 1))
    else
        inactive+=("$d")
    fi
done
for t in "${template_units[@]}"; do
    for i in $(seq 1 "$template_instances"); do
        if systemctl is-active --quiet "${t}@${i}.service" 2>/dev/null; then
            active=$((active + 1))
        else
            [[ -f "/etc/systemd/system/${t}@.service" ]] && inactive+=("${t}@${i}")
        fi
    done
done

log "─────────────────────────────────────────────"
log "BOOTSTRAP COMPLETE"
log "  tier:     $TIER"
log "  install:  $INSTALL_DIR"
log "  user:     $RUN_USER"
log "  env:      $ENV_FILE"
log "  units:    $unit_count installed"
log "  active:   $active / $unit_count"
if [[ ${#inactive[@]} -gt 0 ]]; then
    log "  INACTIVE: ${inactive[*]}"
    log "  → check: journalctl -u <unit> -n 50"
    exit 2
fi
log "  all daemons active ✓"
exit 0
